/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    
    String url = "jdbc:sqlserver://DESKTOP-J10COSF\\SQLEXPRESS:1433;databaseName=crud;user=sa;password=12345;encrypt=false";
    
    public form() {
        initComponents();
        setLocationRelativeTo(null);
            
        Connection con = null;
        
        try {                        
            con  = DriverManager.getConnection(url);
            
            System.out.println("Berhasil ke konek lek");
            ResultSet cn = con.createStatement().executeQuery("SELECT * FROM latihanCRUD");
            
            for (int i = 0; cn.next(); i++){
                ((DefaultTableModel) kotak.getModel()).setRowCount(i+1);
                kotak.setValueAt(cn.getString("NIK"), i, 0);
                kotak.setValueAt(cn.getString("Nama"), i, 1);
                kotak.setValueAt(cn.getString("Telepon"), i, 2);
                kotak.setValueAt(cn.getString("Alamat"), i, 3);
                
            }
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                if(con !=null) {
                    con.close();
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fNIK = new javax.swing.JTextField();
        fNama = new javax.swing.JTextField();
        fTelepon = new javax.swing.JTextField();
        fAlamat = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kotak = new javax.swing.JTable();
        fCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        jLabel3.setText("Telepon");

        jLabel4.setText("Alamat");

        fNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNIKActionPerformed(evt);
            }
        });

        fNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNamaActionPerformed(evt);
            }
        });

        fTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTeleponActionPerformed(evt);
            }
        });

        btnSimpan.setText("SImpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusEvent(evt);
            }
        });

        kotak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIK", "Nama", "Telepon", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(kotak);

        fCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCariActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariEvent(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Data Siswa PPLG");

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
                UbahEvent(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fNIK)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSimpan)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fNama)
                                .addComponent(fAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                .addComponent(fTelepon)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fCari, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCari))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUbah)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(fNama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fAlamat)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnUbah))
                .addGap(221, 221, 221))
        );

        setSize(new java.awt.Dimension(563, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNIKActionPerformed

    private void fTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTeleponActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement stment = null;
        try {                        
            con = DriverManager.getConnection(url);
            stment  = con.prepareStatement("INSERT INTO latihanCRUD (NIK, Nama, Telepon, Alamat) VALUES (?,?,?,?)");
            stment.setInt(1, Integer.parseInt(fNIK.getText()));
            stment.setString(2, fNama.getText());
            stment.setInt(3, Integer.parseInt(fTelepon.getText()));
            stment.setString(4, fAlamat.getText());
            stment.executeUpdate();
            
            ResultSet cn = con.createStatement().executeQuery("SELECT * FROM latihanCRUD");
            
            for (int i = 0; cn.next(); i++){
                ((DefaultTableModel) kotak.getModel()).setRowCount(i+1);
                kotak.setValueAt(cn.getString("NIK"), i, 0);
                kotak.setValueAt(cn.getString("Nama"), i, 1);
                kotak.setValueAt(cn.getString("Telepon"), i, 2);
                kotak.setValueAt(cn.getString("Alamat"), i, 3);
                
            }
            
            fNIK.setText("");
            fNama.setText("");
            fTelepon.setText("");
            fAlamat.setText(null);
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                if (stment != null) {
                    con.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void fNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNamaActionPerformed

    private void fCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCariActionPerformed

    private void CariEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariEvent
        // TODO add your handling code here:
        Connection con = null;
        
        String CariWord = fCari.getText().toLowerCase();
        
        try {                        
            con  = DriverManager.getConnection(url);
            
            System.out.println("Berhasil ke konek lek");
            ResultSet cn = con.createStatement().executeQuery("SELECT * FROM latihanCRUD");
            
            int i = 0;
            while (cn.next()){
                if (cn.getString("Nama").toLowerCase().contains(CariWord)) {
                    ((DefaultTableModel) kotak.getModel()).setRowCount(i+1);
                    kotak.setValueAt(cn.getString("NIK"), i, 0);
                    kotak.setValueAt(cn.getString("Nama"), i, 1);
                    kotak.setValueAt(cn.getString("Telepon"), i, 2);
                    kotak.setValueAt(cn.getString("Alamat"), i, 3);
                    i++; 
                }
            }
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                if(con !=null) {
                    con.close();
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_CariEvent

    private void HapusEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusEvent
        // TODO add your handling code here:
        int pilihan = kotak.getSelectedRow();
        String kunci = kotak.getValueAt(pilihan, 0).toString();
        
        if (pilihan != -1){
            int i; 
            for (i = pilihan; i+1<kotak.getRowCount();i++ ){
                kotak.setValueAt(kotak.getValueAt(i+1,0), i,0);
                kotak.setValueAt(kotak.getValueAt(i+1,1), i,1);
                kotak.setValueAt(kotak.getValueAt(i+1,2), i,2);
                kotak.setValueAt(kotak.getValueAt(i+1,3), i,3);
            }
            ((DefaultTableModel) kotak.getModel()).setRowCount(i);
        }
        
        Connection con = null;
        PreparedStatement stment = null;
        try {                        
            con = DriverManager.getConnection(url);
            String Query = "DELETE FROM latihanCRUD WHERE NIK= ?";
            stment = con.prepareStatement(Query);
            stment.setString(1, kunci);
            stment.executeUpdate();
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                if (stment != null) {
                    con.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_HapusEvent

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void UbahEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahEvent
        // TODO add your handling code here:
    }//GEN-LAST:event_UbahEvent

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField fAlamat;
    private javax.swing.JTextField fCari;
    private javax.swing.JTextField fNIK;
    private javax.swing.JTextField fNama;
    private javax.swing.JTextField fTelepon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kotak;
    // End of variables declaration//GEN-END:variables
}
